repositories:
  remote:
   - https://repo1.maven.org/maven2

artifacts:
  httpclient: org.apache.httpcomponents:httpclient:jar:4.3
  httpcore: org.apache.httpcomponents:httpcore:jar:4.3
  commons_codec: commons-codec:commons-codec:jar:1.8
  commons_logging: commons-logging:commons-logging:jar:1.1.3

  javax_servlet: org.apache.geronimo.specs:geronimo-servlet_3.0_spec:jar:1.0
