repositories:
  remote:
    - https://stocksoftware.jfrog.io/stocksoftware/staging
    - https://stocksoftware.jfrog.io/stocksoftware/maven2
    - https://repo.maven.apache.org/maven2

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  httpclient: org.apache.httpcomponents:httpclient:jar:4.3
  httpcore: org.apache.httpcomponents:httpcore:jar:4.3
  commons_codec: commons-codec:commons-codec:jar:1.8
  commons_logging: commons-logging:commons-logging:jar:1.1.3

  javax_servlet: javax.servlet:javax.servlet-api:jar:4.0.1

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
